version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=matcher_db
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: app
    build:
      context: .
    environment:
      - MYSQL_DATABASE=matcher_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE_HOST=db
      - MYSQL_DATABASE_PORT=3306
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
volumes:
  db:
    driver: local